# Generated by Django 4.1 on 2023-06-04 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("my_pasture", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Member",
            new_name="User",
        ),
    ]
