# Generated by Django 4.1 on 2023-06-08 23:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_pasture", "0003_inputmodel_delete_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inputmodel",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="inputmodel",
            name="kml_file",
            field=models.FileField(
                upload_to="kml_files/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["kml"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="inputmodel",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
